#!/bin/sh

set -euf

cd ${AUTOPKGTEST_TMP}

for py in $(py3versions -s); do
    echo "=== $py ==="
    $py -m twisted.trial \
        --temp-directory=${AUTOPKGTEST_TMP}/_trial_temp_$py \
        --reactor=default \
        --reporter=verbose \
        -e twisted
done
